### ISSUE TITLE
Has error when start app

### ISSUE THREAD

**Issue by dungphanxuan** [adeelibr/node-playground#3]
[nodemon] starting `node server/index.js`
internal/modules/cjs/loader.js:1174
      throw new ERR_REQUIRE_ESM(filename, parentPath, packageJsonPath);
      ^

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: D:\xampp\htdocs\app\node-playground\chapter-1-chat\server\index.js
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1174:13)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47 {
  code: 'ERR_REQUIRE_ESM'
}
[nodemon] app crashed - waiting for file changes before starting...

**Comment by adeelibr** [comment]
What happens when you clone this repository and run it? Also make sure you have the right node version.

**Comment by oengmengthong** [comment]
just add
"type": "module",

in to package.json
